# Form implementation generated from reading ui file 'GalleryForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 575)
        self.galery_table = QtWidgets.QTableWidget(parent=Form)
        self.galery_table.setGeometry(QtCore.QRect(0, 0, 800, 581))
        self.galery_table.setStyleSheet("background-color: #f0f0f0;")
        self.galery_table.setRowCount(1)
        self.galery_table.setColumnCount(3)
        self.galery_table.setObjectName("galery_table")
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.NoItemFlags)
        self.galery_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.NoItemFlags)
        self.galery_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsDragEnabled|QtCore.Qt.ItemFlag.ItemIsDropEnabled|QtCore.Qt.ItemFlag.ItemIsUserCheckable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.galery_table.setItem(0, 2, item)
        self.galery_table.horizontalHeader().setVisible(False)
        self.galery_table.horizontalHeader().setCascadingSectionResizes(False)
        self.galery_table.horizontalHeader().setDefaultSectionSize(500)
        self.galery_table.horizontalHeader().setMinimumSectionSize(50)
        self.galery_table.verticalHeader().setVisible(False)
        self.galery_table.verticalHeader().setDefaultSectionSize(300)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        __sortingEnabled = self.galery_table.isSortingEnabled()
        self.galery_table.setSortingEnabled(False)
        self.galery_table.setSortingEnabled(__sortingEnabled)
