# Form implementation generated from reading ui file 'GalleryForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(524, 392)
        self.to_main_btn = QtWidgets.QPushButton(parent=Form)
        self.to_main_btn.setGeometry(QtCore.QRect(160, 160, 181, 51))
        self.to_main_btn.setObjectName("to_main_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.to_main_btn.setText(_translate("Form", "Вернуться"))
