# Form implementation generated from reading ui file 'MapForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 451)
        self.map_label = QtWidgets.QLabel(parent=Form)
        self.map_label.setGeometry(QtCore.QRect(0, 0, 650, 450))
        self.map_label.setText("")
        self.map_label.setObjectName("map_label")
        self.back_btn = QtWidgets.QPushButton(parent=Form)
        self.back_btn.setGeometry(QtCore.QRect(520, 390, 111, 41))
        self.back_btn.setObjectName("back_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.back_btn.setText(_translate("Form", "Вернуться"))
