# Form implementation generated from reading ui file 'ObservForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 775)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_gallery_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_gallery_btn.setGeometry(QtCore.QRect(950, 670, 151, 41))
        self.open_gallery_btn.setObjectName("open_gallery_btn")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, -10, 591, 781))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        self.choose_file_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.choose_file_btn.setGeometry(QtCore.QRect(600, 670, 151, 41))
        self.choose_file_btn.setObjectName("choose_file_btn")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(590, 20, 51, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_gallery_btn.setText(_translate("MainWindow", "Галерея"))
        self.choose_file_btn.setText(_translate("MainWindow", "Открыть..."))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
